### ISSUE TITLE
EPIC: Harmonize Elyra tutorial with OS-C developer onboarding

### ISSUE THREAD

**Issue by MichaelTiemannOSC** [os-climate/OS-Climate-Community-Hub#54]
This Elyra [tutorial](https://github.com/AICoE/elyra-aidevsecops-tutorial) exposes a lot of details about building the underlying infra for supporting data pipelines.  Most of the demo notebooks take this infra for granted, leading to challenges when pipelines are ready to be implemented "for real".

For this EPIC we need to:

- [ ] Validate/update the basic Elyra tutorial to match current Op1st realities (we don't want to build on out-of-date information)
- [ ] Update Data Commons developer guidance
- [ ] update notebooks in Data Platform Demo that can exemplify good behavior
- [ ] update ingestion pipelines, tagging and/or releasing those that have been properly harmonized

Ideally, this will lead to regularization of how dependencies are managed and how data exploration with Jupyter Notebooks can lead to reproducible data transformation and management with Elyra pipeline nodes that are efficient in the libraries they load and the code they execute.

**Comment by HeatherAck** [comment]
@erikerlandson can you provide support for these tasks?
